---

dist: trusty
sudo: false
language: python

addons:
  apt:
    packages:
      - python-pip
      - p7zip-full
      - unar

before_install:
  - pip install tox

script: tox

notifications:
  email: false

matrix:
  include:
    - python: "2.7"
      env: TOXENV=flake8
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.6"
      env: TOXENV=py36
  allow_failures:
    - python: "3.6"
      env: TOXENV=py36
